name: Code Analisys

on:
  workflow_call:
    secrets:
      ENV_GITHUB_TOKEN:
        required: true
      ENV_SONAR_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: DEV
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn -B package

      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.ENV_GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.ENV_SONAR_TOKEN }}