name: Publish Docker Master

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - uses: actions/checkout@v3

      - name: "🚀 docker push adapter-rest-fast-food"
        run: |
          docker push ${{ secrets.DOCKER_USER }}/adapter-rest-fast-food:latest

      - name: "🚀 docker push adapter-consumer-billing-fast-food"
        run: |
          docker push ${{ secrets.DOCKER_USER }}/adapter-consumer-billing-fast-food:latest